version: '3.9'

services:
  app:
    build: "./env"
    restart: always
    volumes:
      - "./app:/var/www/app"
    ports:
      - 3000:3000
    working_dir: "/var/www/app"


  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: mydb
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

volumes:
  mongodb_data: